CREATE TABLE TEACHER
(
CPF NUMERIC(11) CONSTRAINT PK_TEACHER PRIMARY KEY,
NAME VARCHAR(50) CONSTRAINT NN_NAME_TEACHER NOT NULL,
TELEPHONE NUMERIC(11) CONSTRAINT NN_TELEPHONE_TEACHER NOT NULL,
SALARY NUMERIC(10) CONSTRAINT NN_SALARY_TEACHER NOT NULL
);
CREATE TABLE STUDENT
(
RA NUMERIC(10) CONSTRAINT PK_STUDENT PRIMARY KEY,
NAME VARCHAR(70) CONSTRAINT NN_NAME_STUDENT NOT NULL,
CPF NUMERIC(11) CONSTRAINT UN_CPF_STUDENT UNIQUE CONSTRAINT NN_CPF_STUDENT NOT NULL,
COURSE VARCHAR(40) CONSTRAINT NN_COURSE_STUDENT NOT NULL
);

CREATE TABLE SUBJECT
(
IDCLASS SERIAL CONSTRAINT PK_SUBJECT PRIMARY KEY,
NAME VARCHAR(50) CONSTRAINT NN_SUBJECT_NAME NOT NULL,
TOTALHOURS INT CONSTRAINT NN_HOURS NOT NULL,
CPFTEACHER NUMERIC(11),
CONSTRAINT FK_CPF_TEACHER FOREIGN KEY(CPFTEACHER) REFERENCES TEACHER(CPF)
);

CREATE TABLE ENROLLMENT
(
IDENROLL SERIAL CONSTRAINT PK_ENROLLMENT PRIMARY KEY,
IDCLASS INT,
RA NUMERIC(10),
CONSTRAINT FK_ID_SUBJECT_ENROLLMENT FOREIGN KEY(IDCLASS) REFERENCES SUBJECT(IDCLASS),
CONSTRAINT FK_RA_STUDENT_ENROLLMENT FOREIGN KEY(RA) REFERENCES STUDENT(RA)
)

